source = ~/.config/hypr/config/colors.conf
general {
    gaps_in = 3
    gaps_out = 5
    border_size = 3
    col.active_border = $accent
    col.inactive_border = $accent_dim
    layout = dwindle
}
dwindle { preserve_split = true }
misc {
    disable_hyprland_logo = true
    focus_on_activate = true
    vrr = 2
}
gesture = 4, horizontal, workspace

